name: Windows - UI Automated Tests - Build App and Run Tests ğŸ§ª

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        run: ["windows.ci", "windows.chatA", "windows.chatB"]

    steps:
      - name: Checkout testing directory ğŸ”–
        uses: actions/checkout@v3

      - name: Setup Node.js ğŸ”¨
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Cache NPM dependencies ğŸ”¨
        uses: actions/cache@v3
        id: cache-appium
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install NPM dependencies ğŸ“¦
        if: steps.cache-appium.outputs.cache-hit != 'true'
        run: npm ci

      #- name: Download the app ğŸ—³ï¸
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: Uplink-Windows
      #    path: ./apps

      - name: Install and Run Appium Server ğŸ’»
        run: |
          npm install -g appium@next
          appium -v
          appium driver install --source=npm appium-windows-driver
          appium driver list

      - name: Delete cache folder before starting
        run: If (Test-Path $home/.uplink) {Remove-Item -Recurse -Force $home/.uplink} Else { Break }
        shell: powershell

      - name: Run WebdriverIO tests on Windows ğŸ§ª
        run: npm run ${{ matrix.run }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: |
          always() && matrix.run == 'windows.ci'
        with:
          junit_files: "./test-report/*.xml"
          check_name: "UI Automated Test Results on Windows"

      - name: Upload Screenshots ğŸ“·
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots-${{ matrix.run }}
          path: ./test-results

      - name: Upload Appium Log ğŸ“·
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log-${{ matrix.run }}
          path: ./appium.log
